---
argument_specs:
  main:
    short_description: netconf-interface
    description:
      - Write or remove vlans
    author:
      - Christian Knoblauch

    options:
      current_config:
        type: str
        required: false
        description: >
          Complete device configuration including all vlans

      # add_vlans:
      #   type: list
      #   description: >
      #     a list of vlans to add
      #     - vlan_id: 123
      #       name: Test

      replace:
        type: bool
        required: false
        default: false
        description: >
          Use only if set to true. If merge is defined remove vlans is not used, but only 'add_vlans' will remain on the device.

      # remove_vlans:
      #   type: list
      #   elements: int
      #   required: false
      #   default: false
      #   description: >
      #     A list of vlan IDs to remove
      #       - 123
      #       - 200
      #       - ...

