---
argument_specs:
  main:
    short_description: netconf-interface
    description:
      - Write interface configuration.
    author:
      - Christian Knoblauch

    options:
      name:
        type: str
        required: true
        description: Interface name e.g. GigabitEhternet1/0/1

      current_config:
        required: false
        description: >
          A list with all configuration lines which are now found on the interface. Get them using role getConfiguration. It returns netconfrpc.interfaces.

      intended_config:
        type: list
        elements: str
        required: true
        description: >
          A list of configuration commands send to the device

      default_interface:
        type: bool
        required: false
        default: false
        description: send 'default interface name' before config is send

      default_config:
        type: list
        elements: str
        required: false
        description: >
          Lines which are not visible after sending them to the configuration.These are usually
          default commands like 'logging event link-status'. If you don't want logging you need to add
          'no logging event link-status' to target_config, since you will see it ins the running config.

