---
- name: Edit vlans
  hosts: all
  gather_facts: no
  vars:
    ansible_user: test
    ansible_ssh_pass: test
    ansible_network_os: cisco.ios.ios
    ansible_connection: ansible.netcommon.netconf	
    ansible_become: yes
    ansible_become_method: enable
    ansible_port: 22


  tasks:



    - name: Get running configuration
      include_role:
        name: netconfrpc/getConfiguration

    - name: Set only configured vlans!
      vars:
        current_configuration: "{{ netconfrpc_result.stdout_lines }}"
        debug: true
        add_vlans:
          - vlan_id: 100
            name: Office
          - vlan_id: 200
            name: Data
          - vlan_id: 555
            name: Management
          - vlan_id: 888
            name: SuperSecret
        replace: true
      include_role:
        name: netconfrpc/vlans

