---


- name: Parse block configuration ()
  set_fact:
    block_config: "{{ current_config | extract_block(start_block, end_block) }}"


- name: Current config found for block_config
  debug:
    msg: 
      - "{{ block_config }}"
  when: debug


- name: check if config is different
  set_fact:
    unwanted_lines: "{{ block_config | difference(intended_config) }}"
    missing_lines: "{{ intended_config | difference(block_config) }}"

- name: Debug diff
  debug: 
    msg:
      - Unwanted lines in your block
      - "{{ unwanted_lines }}"
      - Missing lines (difference between intended and current configuration)
      - "{{ missing_lines }}"
  when: debug | bool == true

- name: set before_list if string
  set_fact:
    before_list: [ before ]
  when: before | type_debug == 'AnsibleUnicode'

- name: Set before type if list
  set_fact:
    before_list: "{{ before }}"
  when: before | type_debug == 'list'

- name: prepare push_stack = before + start_block + intended_config + default_config
  set_fact:
    push_stack: "{{ before + [ start_block ] + intended_config + default_config }}"

- name: debug push_stack
  debug:
    msg: "{{ push_stack }}"
  when: debug | bool == true



- name: Send push_stack to device
  when:
    - (missing_lines|length != 0) or (unwanted_lines|length != 0)
    - ansible_check_mode == false
  register: result_conf
  changed_when: true
  notify: write running configuration
  ansible.netcommon.netconf_rpc:
    rpc: edit-config
    content: |
      <target>
      <running/>
      </target>
        <config>
        <cli-config-data>
        {% for cmd in push_stack %}
        <cmd>{{ cmd }}</cmd>
        {% endfor %}
        </cli-config-data>
        </config>      
  register: output

- name: debug edit-config output
  debug:
    msg: "{{ output }}"
  when: debug | bool == true

