---


# + end am Ende, weil show running | s interfaces kein ! oder end am Ende hat
# ?=(interface|end|!) holt den Inhalt bis zum nächsten interface, end oder ! am Ende. Die ! werden gebraucht wenn man die komplette config zieht.
- name: Get interface configuration
  set_fact:
    current_config_lines: "{{ current_config[name] }}"

- name: Current config found on interface
  debug:
    msg: 
      - "{{ current_config_lines }}"
  when: debug == 'true'

- name: check if config is different
  set_fact:
    diff_c_to_i: "{{ current_config_lines | difference(intended_config) }}"
    diff_i_to_c: "{{ intended_config | difference(current_config_lines) }}"

- name: diff
  debug: 
    msg:
      - Current to intended config
      - "{{ diff_c_to_i }}"
      - Intended to current config
      - "{{ diff_i_to_c }}"
  when: debug | bool == true

- name: prepare default interface 
  set_fact:
    push_stack: "{{ ['default interface '+name] }}"
  when: default_interface | bool == true

- name: prepare config
  set_fact:
    push_stack: "{{ push_stack + ['interface '+name] + intended_config + default_config }}"

- name: Pushstack
  debug:
    msg: "{{ push_stack }}"
  when: debug | bool == true

- name: Send config to device
  when:
    - (diff_i_to_c|length != 0) or (diff_c_to_i|length != 0)
    - ansible_check_mode == False
  register: result_conf
  changed_when: true
  notify: write running configuration
  ansible.netcommon.netconf_rpc:
    rpc: edit-config
    content: |
      <target>
      <running/>
      </target>
        <config>
        <cli-config-data>
        {% for cmd in push_stack %}
        <cmd>{{ cmd }}</cmd>
        {% endfor %}
        </cli-config-data>
        </config>      


# - name: rpc routput
#   debug:
#     msg: "{{ result_conf }}"


# - name: Send config to device
#   when: (diff_i_to_c|length > 0) or (diff_c_to_i|length != 0)
#   register: result_conf      
#   ansible.netcommon.netconf_rpc:
#     rpc: edit-config
#     content: |
#       <target>
#       <running/>
#       </target>
#         <config>
#         <cli-config-data>
#         {% if default %}
#         <cmd>default interface {{ name }}</cmd>
#         {% endif %}
#         <cmd>interface {{ name }}</cmd>
#         {% for cmd in intended_config %}
#         <cmd>{{ cmd }}</cmd>
#         {% endfor %}
#         {% for cmd in default_config %}
#         <cmd>{{ cmd }}</cmd>
#         {% endfor %}
#         </cli-config-data>
#         </config>      

