---
argument_specs:
  main:
    short_description: blockConfig
    description:
      - Make sure all lines from a block of configuration is present or removed. This role can be used for access lists or any other block. It doesn't need to be an indewnted block of config like access-lists or class-maps.
    author:
      - Christian Knoblauch
    options:
      start_block:
        type: str
        required: true
        description: >
          a line of code to start a config block: 'ip access-list standard MGMT'

      end_block:
        type: str
        required: true
        description: >
          a line of configuration to end a config block: '!'

      before:
        type: list
        elements: str
        required: false
        description: >
          commands you need to fix things up like deleting an access-list completly

      default_config:
        type: list
        elements: str
        required: false
        description: >
          A list of commands which are not visible in the final configuration

      current_config:
        type: list
        elements: str
        required: true
        description: >
          your current complete device config as string

