- name: write running configuration
  ansible.netcommon.netconf_rpc:
          rpc: copy-config
          content: |
            <source><running/></source>
            <target>
              <startup/>
            </target>